trigger:
- workspace_publish

pool:
  vmImage: ubuntu-latest


steps:
- bash: |
    pwd
    cd syn-dev-eus01
    ls -l
  displayName: Multiline Bash Script
  env:
    name: Microsoft
- task: Synapse workspace deployment@2
  displayName: 'Synpase deployment task for workspace: syn-$(env)-data-eus '

  inputs:
    operation: 'validateDeploy'
    ArtifactsFolder: '/home/vsts/work/1/s/promitxi_synapserepo/syn-dev-eus01/'
    azureSubscription: 'Promit''s Cloud(3)(58a3cb06-91b3-4f09-82b8-882ec0a9c038)'
    ResourceGroupName: 'RG-Test-QA-Data-RG'
    TargetWorkspaceName: 'syn-$(env)-data-eus'
    DeleteArtifactsNotInTemplate: false
    DeployManagedPrivateEndpoints: false
    OverrideArmParameters: '-workspaceName $(env)'
    FailOnMissingOverrides: true
    Environment: 'prod'
    npmpackage: 'prod'
