trigger:
- workspace_publish

pool:
  vmImage: ubuntu-latest

variables:
  env: 'qa'
  workspace: 'syn-$(env)-data-eus'


steps:

- bash: |
    pwd
    
    ls -l
  displayName: Multiline Bash Script
  env:
    name: Microsoft


- task: AzureSynapseWorkspace.synapsecicd-deploy.synapse-deploy.Synapse workspace deployment@2
  displayName: 'Synpase deployment task for workspace: syn-$(env)-data-eus '
  inputs:
    TemplateFile: '/home/vsts/work/1/s/syn-dev-eus01/TemplateForWorkspace.json'
    ParametersFile: '/home/vsts/work/1/s/syn-dev-eus01/TemplateParametersForWorkspace.json'
    azureSubscription: 'Promit''s Cloud(3)(58a3cb06-91b3-4f09-82b8-882ec0a9c038)'
    ResourceGroupName: 'RG-Test-QA-Data-RG'
    TargetWorkspaceName: 'syn-$(env)-data-eus '
    OverrideArmParameters: '-workspaceName $(env)'
    npmpackage: ppe