trigger:
- workspace_publish

pool:
  vmImage: ubuntu-latest

variables:
  env: 'qa'

steps:
- bash: |
    pwd
    cd syn-dev-eus01
    ls -l
  displayName: Multiline Bash Script
  env:
    name: Microsoft
- task: AzureSynapseWorkspace.synapsecicd-deploy.synapse-deploy.Synapse workspace deployment@2
  displayName: 'Synpase deployment task for workspace: syn-$(env)-data-eus '
  inputs:
    TemplateFile: '$(System.DefaultWorkingDirectory)/_PromitXI_promitxi_synapserepo/syn-dev-eus01/TemplateForWorkspace.json'
    ParametersFile: '$(System.DefaultWorkingDirectory)/_PromitXI_promitxi_synapserepo/syn-dev-eus01/TemplateParametersForWorkspace.json'
    azureSubscription: 'Promit''s Cloud(3)(58a3cb06-91b3-4f09-82b8-882ec0a9c038)'
    ResourceGroupName: 'RG-Test-QA-Data-RG'
    TargetWorkspaceName: 'syn-$(env)-data-eus '
    OverrideArmParameters: '-workspaceName $(env)'
    npmpackage: ppe