# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- workspace_publish

pool:
  vmImage: ubuntu-latest


steps:
- task: AzureSynapseWorkspace.synapsecicd-deploy.synapse-deploy.Synapse workspace deployment@2
  displayName: 'Synpase deployment task for workspace: syn-$(env)-data-eus '

  inputs:
    operation: 'validateDeploy'
    ArtifactsFolder: 'syn-dev-eus01'
    azureSubscription: 'Promit''s Cloud(3)(58a3cb06-91b3-4f09-82b8-882ec0a9c038)'
    ResourceGroupName: 'RG-Test-QA-Data-RG'
    TargetWorkspaceName: 'syn-$(env)-data-eus'
    DeleteArtifactsNotInTemplate: false
    DeployManagedPrivateEndpoints: false
    OverrideArmParameters: '-workspaceName $(workspace)'
    FailOnMissingOverrides: false
    Environment: 'prod'
    npmpackage: 'prod'

